---
- name: Provisionar VM com Docker e subir stack Wordpress
  hosts: all
  become: true
  gather_facts: true

  vars:
    stack_dir: /opt/wordpress_stack

  tasks:
    - name: Atualizar cache APT e pacotes
      apt:
        update_cache: yes
        upgrade: dist

    - name: Instalar dependências do Docker (pacotes Debian)
      apt:
        name:
          - docker.io
          - docker-compose-plugin
          - python3-pip
        state: present

    - name: Garantir serviço docker ativo
      service:
        name: docker
        state: started
        enabled: yes

    - name: Adicionar usuário vagrant ao grupo docker
      user:
        name: vagrant
        groups: docker
        append: yes

    - name: Criar diretório do stack
      file:
        path: "{ stack_dir }"
        state: directory
        mode: "0755"

    - name: Copiar docker-compose.yml do diretório compartilhado
      copy:
        src: /vagrant/docker-compose.yml
        dest: "{ stack_dir }/docker-compose.yml"
        mode: "0644"

    - name: Subir stack com Docker Compose
      command: docker compose up -d
      args:
        chdir: "{ stack_dir }"

    - name: Exibir URL de acesso
      debug:
        msg: "Acesse http://192.168.56.145:8080 para abrir o Wordpress via webproxy Nginx."
