Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"

  # Hostname according to project rules
  config.vm.hostname = "sergio.henrique"

  # Private network IP 192.168.56.1XY (XY = 45)
  config.vm.network "private_network", ip: "192.168.56.145"

  # Disable SSH key insertion (generation deactivated)
  config.ssh.insert_key = false

  # Provider: VirtualBox
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 1024
    vb.cpus = 1
    vb.check_guest_additions = false
    vb.linked_clone = true
  end

  # Ensure /vagrant is synced (default). We'll use ansible_local so no host-side Ansible required.
  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "playbook_ansible.yml"
    ansible.become = true
  end
end
